all: Proposal-DuBuisson-Sackville-West.pdf

Proposal-DuBuisson-Sackville-West.pdf: Proposal.tex Proposal.bib
	pdflatex Proposal.tex
	pdflatex Proposal.tex
	bibtex Proposal
	pdflatex Proposal.tex
	pdflatex Proposal.tex
	pdflatex Proposal.tex
	bibtex Proposal
	pdflatex Proposal.tex

